/*!

* This file outlines routes (used to generate Sidebar links).
*     NOTE: actual URLs are generated by NextJS using files in pages/ folder.

*/
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import {
    faTachometer,
} from '@fortawesome/pro-light-svg-icons';

const getAppRoutes = ( userId ) => {
    let dashboardViews = [
        {
            path: "/",
            name: "Dashboard",
            miniName: "Dsh",
            layout: "",
        }
    ];
    
    if( 0 == userId ){
        dashboardViews.push(
            {
                path: "/bedroom1",
                name: "Bedroom",
                miniName: "Br",
                layout: "",
            }
        );
        dashboardViews.push(
            {
                path: "/server",
                name: "Server",
                miniName: "Srv",
                layout: "",
            }
        );
    } else if ( 1 == userId ){
        dashboardViews.push(
            {
                path: "/bedroom0",
                name: "Bedroom",
                miniName: "Br",
                layout: "",
            }
        );
    }
    
    dashboardViews.push(
        {
            path: "/vents",
            name: "Vents",
            miniName: "Vnt",
            layout: "",
        }
    );
    
    dashboardViews.push(
        {
            path: "/garage",
            name: "Garage",
            miniName: "Grg",
            layout: "",
        }
    );
    
    return [
        {
            collapse: true,
            name: "Dashboards",
            icon: faTachometer,
            state: "dashboardsCollapse",
            noUser: true, //allow when not logged in?
            views: dashboardViews,
        }
    ];
};

export default getAppRoutes;
