/*!

* This file outlines routes (used to generate Sidebar links).
*     NOTE: actual URLs are generated by NextJS using files in pages/ folder.

*/
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import {
    faTachometer,
} from '@fortawesome/pro-light-svg-icons';

const getAppRoutes = ( userId ) => {
    let dashboardViews = [
        {
            path: "/",
            name: "Dashboard",
            miniName: "Dsh",
            layout: "",
        },
        {
            path: "/garage",
            name: "Garage",
            miniName: "Grg",
            layout: "",
        },
        {
            path: "/vents",
            name: "Vents",
            miniName: "Vnt",
            layout: "",
        },
    ];
    
    if( 0 == userId ){
        dashboardViews.push(
            {
                path: "/seakers",
                name: "Speakers",
                miniName: "Spk",
                layout: "",
            }
        );
        // dashboardViews.push(
        //     {
        //         path: "/blinds",
        //         name: "Blinds",
        //         miniName: "B",
        //         layout: "",
        //     }
        // );
        dashboardViews.push(
            {
                path: "/server",
                name: "Server",
                miniName: "Srv",
                layout: "",
            }
        );
    }
    
    return [
        {
            collapse: true,
            name: "Dashboards",
            icon: faTachometer,
            state: "dashboardsCollapse",
            noUser: true, //allow when not logged in?
            views: dashboardViews,
        }
    ];
};

export default getAppRoutes;
